### ISSUE TITLE
OSError: [Errno 122] Disk quota exceeded

### ISSUE THREAD

**Issue by tongjiezhao** [aristoteleo/spateo-release#120]
Hi BGIer new to python. I got this error when I import spateo in linux python
import spateo as st
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-nstdpwph because the default path (/home/zhaotongjie/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib is building the font cache; this may take a moment.
2022-05-18 09:48:17.694351: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/opencv_python-4.5.5.64-py3.8-linux-x86_64.egg/cv2/../../lib64:/opt/gridengine/lib/lx-amd64:/opt/gridengine/lib/lx-amd64:/opt/openmpi/lib
2022-05-18 09:48:17.694409: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/__init__.py", line 10, in <module>
    from . import cs, io, pl, pp, tdr, tl
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/pl.py", line 1, in <module>
    from .plotting import *
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/plotting/__init__.py", line 5, in <module>
    from .static import *
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/plotting/static/__init__.py", line 5, in <module>
    from .colorlabel import color_label
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/plotting/static/colorlabel.py", line 6, in <module>
    from .scatters import scatters
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/plotting/static/scatters.py", line 19, in <module>
    from spateo.tools.utils import (
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/tools/__init__.py", line 20, in <module>
    from .lisa import GM_lag_model, lisa_geo_df, local_moran_i
  File "/jdfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/source/spateo-release/spateo/tools/lisa.py", line 15, in <module>
    from pysal import explore
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/pysal-2.6.0-py3.8.egg/pysal/explore/__init__.py", line 1, in <module>
    import esda
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/esda-2.4.1-py3.8.egg/esda/__init__.py", line 7, in <module>
    from . import adbscan
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/esda-2.4.1-py3.8.egg/esda/adbscan.py", line 10, in <module>
    from libpysal.cg.alpha_shapes import alpha_shape_auto
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/libpysal-4.6.2-py3.8.egg/libpysal/__init__.py", line 26, in <module>
    from . import examples
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/libpysal-4.6.2-py3.8.egg/libpysal/examples/__init__.py", line 7, in <module>
    from .base import example_manager
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/libpysal-4.6.2-py3.8.egg/libpysal/examples/base.py", line 96, in <module>
    class Example:
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/libpysal-4.6.2-py3.8.egg/libpysal/examples/base.py", line 135, in Example
    def get_local_path(self, path=get_data_home()) -> str:
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/site-packages/libpysal-4.6.2-py3.8.egg/libpysal/examples/base.py", line 40, in get_data_home
    makedirs(data_home, exist_ok=True)
  File "/hwfssz1/ST_SUPERCELLS/P20Z10200N0059/panhailin/software/executable/miniconda3/envs/spateo/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 122] Disk quota exceeded: '/home/zhaotongjie/.local/share/pysal

How to solve this problem?
thx

**Comment by Xiaojieqiu** [comment]
Dear @tongjiezhao thanks for using spateo. The error you found shows that the disk quota for your account is full. You may consider asking the administer to increase it or delete unnecessary files / folders on your disk
