### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by JLiLab** [aristoteleo/spateo-release#194]
Hi, 
Thank you for creating and sharing the package. After using pip install git+https://github.com/aristoteleo/spateo-release, I ran into an error about missing "spate.external" when I tried to import spateo. Here is the complete message:

import spateo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/__init__.py", line 9, in <module>
    from . import align, cs, dd, io, pl, pp, sample_data, svg, tdr, tl
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/align.py", line 1, in <module>
    from .alignment import (
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/alignment/__init__.py", line 1, in <module>
    from .deformation import grid_deformation
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/alignment/deformation.py", line 14, in <module>
    from .transform import BA_transform
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/alignment/transform.py", line 8, in <module>
    from .methods import cal_dist, cal_dot
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/alignment/methods/__init__.py", line 1, in <module>
    from .morpho import BA_align
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/alignment/methods/morpho.py", line 15, in <module>
    from spateo.logging import logger_manager as lm
  File "/Users/jamesli/miniconda3/envs/spateo/lib/python3.9/site-packages/spateo/logging.py", line 1, in <module>
    from .external import lack
ModuleNotFoundError: No module named 'spateo.external'

**Comment by Sichao25** [comment]
Hi, thank you very much for reporting the issue. This may be related to one of our current updates. I will take a look at this and fix it ASAP. Before it is fixed, you can install an older Pypi version of spateo, or install from any specific commit before [pull request 187](https://github.com/aristoteleo/spateo-release/pull/187). You can do this by `pip install git+https://github.com/aristoteleo/spateo-release@<commit hash>`.
